runtime: go
api_version: go1
application: {[{Tok3n_AppName}]}
version: 1
module: default


# inbound_services:
# - warmup

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 1.0s

handlers:
# - url: /
#   script: _go_app
#   secure: always
# - url: /_ah/warmup
#   script: _go_app
#   secure: always
# - url: /warmup
#   script: _go_app
#   secure: always

- url: /
  static_dir: web/
  secure: always